### ISSUE TITLE
Remote Supabase Install Failed

### ISSUE THREAD

**Issue by gestalts** [marmelab/atomic-crm#75]
**What you were expecting:**
Install of  a remote supabase project

**What happened instead:**
The remote install script failed since the superbase installed version did not wait for the verification code.  The script had a message that supabase CLI was not the latest, so I performed an npm upgrade on supabase.  The script now waits for the verification code, but it fails with:  

Enter your verification code: XXXXXX
Token cli_williamloftus@Mac.local_XXXXXXX created successfully.

You are now logged in. Happy coding!
? Enter the name of the project: Atomic CRM
? Enter a database password: XXXXXX
file:///Users/XXXXXX/WebstormProjects/atomic-crm/scripts/supabase-remote-init.mjs:62
    )[1];
     ^

TypeError: Cannot read properties of null (reading '1')
    at createProject (file:///Users/XXXXXX/WebstormProjects/atomic-crm/scripts/supabase-remote-init.mjs:62:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/XXXXXX/WebstormProjects/atomic-crm/scripts/supabase-remote-init.mjs:16:24

Node.js v23.1.0
make: *** [supabase-remote-init] Error 1

**Steps to reproduce:**

make supabase-remote-init 

**Related code:**

* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* atomic-crm version: 0.2
* Last version that did not exhibit the issue (if applicable): N/A
* React version:

├── @chromatic-com/storybook@1.9.0
├── @hello-pangea/dnd@16.6.0
├── @inquirer/prompts@5.3.6
├── @mui/icons-material@5.16.6
├── @mui/material@5.16.6
├── @nivo/bar@0.87.0
├── @nivo/core@0.87.0
├── @storybook/addon-essentials@8.3.0
├── @storybook/addon-interactions@8.3.0
├── @storybook/addon-links@8.3.0
├── @storybook/addon-onboarding@8.3.0
├── @storybook/blocks@8.3.0
├── @storybook/react-vite@8.3.0
├── @storybook/react@8.3.0
├── @storybook/test@8.3.0
├── @supabase/supabase-js@2.45.0
├── @testing-library/jest-dom@6.5.0
├── @testing-library/react@16.0.0
├── @testing-library/user-event@14.5.2
├── @types/faker@5.5.9
├── @types/jest@29.5.12
├── @types/jsonexport@3.0.5
├── @types/lodash@4.17.7
├── @types/papaparse@5.3.14
├── @types/pg@8.11.6
├── @types/react-dom@18.3.0
├── @types/react@18.3.3
├── @vitejs/plugin-react@4.3.1
├── clsx@2.1.1
├── date-fns@3.6.0
├── dotenv@16.4.5
├── eslint-config-prettier@9.1.0
├── eslint-config-react-app@7.0.1
├── eslint-plugin-cypress@2.15.2
├── eslint-plugin-prettier@5.2.1
├── eslint-plugin-storybook@0.8.0
├── eslint-plugin-testing-library@5.11.1
├── eslint@8.57.0
├── execa@9.3.0 (git+ssh://git@github.com/sindresorhus/execa.git#f9f7140e18c41f49315b953a6ae7294b4c1d446e)
├── faker@5.4.0
├── gh-pages@6.1.1
├── ink@5.0.1
├── lint-staged@13.3.0
├── lodash@4.17.21
├── papaparse@5.4.1
├── pg@8.12.0
├── prettier@3.2.5
├── prop-types@15.8.1
├── ra-data-fakerest@5.3.0
├── ra-supabase@3.2.1
├── react-admin@5.3.0
├── react-cropper@2.3.3
├── react-dom@18.3.1
├── react-error-boundary@4.0.13
├── react-router-dom@6.26.0
├── react-router@6.26.0
├── react@18.3.1
├── rollup-plugin-visualizer@5.12.0
├── serve@14.2.3
├── storybook@8.3.0
├── supabase@1.223.10
├── typescript@5.5.4
├── vite-plugin-dts@4.2.1
├── vite@5.3.5
├── vitest@2.0.5
└── web-vitals@4.2.2

* Browser: Firefox 
* Stack trace (in case of a JS error):

file:///Users/XXXXXX/WebstormProjects/atomic-crm/scripts/supabase-remote-init.mjs:62
    )[1];
     ^

TypeError: Cannot read properties of null (reading '1')
    at createProject (file:///Users/XXXXXX/WebstormProjects/atomic-crm/scripts/supabase-remote-init.mjs:62:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/XXXXXX/WebstormProjects/atomic-crm/scripts/supabase-remote-init.mjs:16:24

**Comment by gestalts** [comment]
A few other data points:   The package.json uses "supabase": "^1.136.3".   That version of supabase CLI did not wait for the verification code.  I upgraded to 1.223.10, and the remote install process now waits for the verification.  However, after entering the verification code, I get the error described above.

**Comment by fzaninotto** [comment]
Thanks for the report. It seems Supabase has added additional security checks on the admin API. We'll look into it!

**Comment by fzaninotto** [comment]
Can you try again? We fixed the init script in #76.

**Comment by Farrit1184** [comment]
I am getting something similar (but..different?)

`You are now logged in. Happy coding!
A new version of Supabase CLI is available: v2.24.3 (currently installed
We recommend updating regularly for new features and bug fixes: https://ase-cli
✔ Enter the name of the project: Atomic CRM
file:///media/storage/atomic-crm/scripts/supabase-remote-init.mjs:205
    const password = crypto
                                 ^

ReferenceError: crypto is not defined
    at generatePassword (file:///media/storage/atomic-crm/scripts/supaba
    at file:///media/storage/atomic-crm/scripts/supabase-remote-init.mjs

Node.js v18.19.1
make: *** [makefile:44: supabase-remote-init] Error 1`

It won't even let me get past the point of naming the project before the script fails. Is this an issue on my end, or something between the script and supabase?

**Comment by slax57** [comment]
@Farrit1184 I have just tried running the script again, and it worked flawlessly.
One thing to note however is that I am using Node v20.
You should avoid using Node v18 since it no longer receives security updates.
Does it work better with Node 20?
